#!/bin/bash



# Installation program for projia.
# This program removes itself when installation finished.
mv Projia $HOME/.projia                                                   && \
ln -s     $HOME/.projia/run $HOME/.bash_tools/projia                      && \
rm $HOME/.projia/install                                                  && \
echo "Projia installation done (you can find it in ~/.projia)."
